// Code generated by "hcl2-schema -type OMIConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*OMIConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"OMIName":                 &hcldec.AttrSpec{Name: "omi_name", Type: cty.String, Required: false},
		"OMIDescription":          &hcldec.AttrSpec{Name: "omi_description", Type: cty.String, Required: false},
		"OMIVirtType":             &hcldec.AttrSpec{Name: "omi_virtualization_type", Type: cty.String, Required: false},
		"OMIAccountIDs":           &hcldec.AttrSpec{Name: "omi_account_ids", Type: cty.List(cty.String), Required: false},
		"OMIGroups":               &hcldec.AttrSpec{Name: "omi_groups", Type: cty.List(cty.String), Required: false},
		"OMIProductCodes":         &hcldec.AttrSpec{Name: "omi_product_codes", Type: cty.List(cty.String), Required: false},
		"OMIRegions":              &hcldec.AttrSpec{Name: "omi_regions", Type: cty.List(cty.String), Required: false},
		"OMISkipRegionValidation": &hcldec.AttrSpec{Name: "skip_region_validation", Type: cty.Bool, Required: false},
		"OMITags":                 &hcldec.BlockAttrsSpec{TypeName: "tags", ElementType: cty.String, Required: false},
		"OMIForceDeregister":      &hcldec.AttrSpec{Name: "force_deregister", Type: cty.Bool, Required: false},
		"OMIForceDeleteSnapshot":  &hcldec.AttrSpec{Name: "force_delete_snapshot", Type: cty.Bool, Required: false},
		"SnapshotTags":            &hcldec.BlockAttrsSpec{TypeName: "snapshot_tags", ElementType: cty.String, Required: false},
		"SnapshotAccountIDs":      &hcldec.AttrSpec{Name: "snapshot_account_ids", Type: cty.List(cty.String), Required: false},
		"SnapshotGroups":          &hcldec.AttrSpec{Name: "snapshot_groups", Type: cty.List(cty.String), Required: false},
	}
	return s
}
