// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package manifest

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"OutputPath": &hcldec.AttrSpec{Name: "output", Type: cty.String, Required: false},
		"StripPath":  &hcldec.AttrSpec{Name: "strip_path", Type: cty.Bool, Required: false},
		"CustomData": &hcldec.BlockAttrsSpec{TypeName: "custom_data", ElementType: cty.String, Required: false},
	}
	return s
}
