// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package iso

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"DiskSize":           &hcldec.AttrSpec{Name: "disk_size", Type: cty.Number, Required: false},
		"DiskType":           &hcldec.AttrSpec{Name: "disk_type", Type: cty.String, Required: false},
		"GuestOSType":        &hcldec.AttrSpec{Name: "guest_os_type", Type: cty.String, Required: false},
		"HardDriveInterface": &hcldec.AttrSpec{Name: "hard_drive_interface", Type: cty.String, Required: false},
		"HostInterfaces":     &hcldec.AttrSpec{Name: "host_interfaces", Type: cty.List(cty.String), Required: false},
		"SkipCompaction":     &hcldec.AttrSpec{Name: "skip_compaction", Type: cty.Bool, Required: false},
		"VMName":             &hcldec.AttrSpec{Name: "vm_name", Type: cty.String, Required: false},
	}
	for k, v := range (&Config{}).HTTPConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).ISOConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).FloppyConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).BootConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).OutputConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).HWConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).PrlctlConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).PrlctlPostConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).PrlctlVersionConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).ShutdownConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).SSHConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).ToolsConfig.HCL2Spec() {
		s[k] = v
	}
	return s
}
