// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package digitaloceanimport

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"APIToken":     &hcldec.AttrSpec{Name: "api_token", Type: cty.String, Required: false},
		"SpacesKey":    &hcldec.AttrSpec{Name: "spaces_key", Type: cty.String, Required: false},
		"SpacesSecret": &hcldec.AttrSpec{Name: "spaces_secret", Type: cty.String, Required: false},
		"SpacesRegion": &hcldec.AttrSpec{Name: "spaces_region", Type: cty.String, Required: false},
		"SpaceName":    &hcldec.AttrSpec{Name: "space_name", Type: cty.String, Required: false},
		"ObjectName":   &hcldec.AttrSpec{Name: "space_object_name", Type: cty.String, Required: false},
		"SkipClean":    &hcldec.AttrSpec{Name: "skip_clean", Type: cty.Bool, Required: false},
		"Tags":         &hcldec.AttrSpec{Name: "image_tags", Type: cty.List(cty.String), Required: false},
		"Name":         &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"Description":  &hcldec.AttrSpec{Name: "image_description", Type: cty.String, Required: false},
		"Distribution": &hcldec.AttrSpec{Name: "image_distribution", Type: cty.String, Required: false},
		"ImageRegions": &hcldec.AttrSpec{Name: "image_regions", Type: cty.List(cty.String), Required: false},
		"Timeout":      &hcldec.AttrSpec{Name: "timeout", Type: cty.String, Required: false},
	}
	return s
}
