// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package bsu

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"VolumeRunTags": &hcldec.BlockAttrsSpec{TypeName: "run_volume_tags", ElementType: cty.String, Required: false},
	}
	for k, v := range (&Config{}).AccessConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).OMIConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).BlockDevices.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).RunConfig.HCL2Spec() {
		s[k] = v
	}
	return s
}
