// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package oneandone

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Token":          &hcldec.AttrSpec{Name: "token", Type: cty.String, Required: false},
		"Url":            &hcldec.AttrSpec{Name: "url", Type: cty.String, Required: false},
		"SnapshotName":   &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"DataCenterName": &hcldec.AttrSpec{Name: "data_center_name", Type: cty.String, Required: false},
		"DataCenterId":   &hcldec.AttrSpec{Name: "datacenterid", Type: cty.String, Required: false},
		"Image":          &hcldec.AttrSpec{Name: "source_image_name", Type: cty.String, Required: false},
		"DiskSize":       &hcldec.AttrSpec{Name: "disk_size", Type: cty.Number, Required: false},
		"Retries":        &hcldec.AttrSpec{Name: "retries", Type: cty.Number, Required: false},
	}
	return s
}
