// Code generated by "hcl2-schema -type TencentCloudImageConfig"; DO NOT EDIT.\n

package cvm

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*TencentCloudImageConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"ImageName":          &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"ImageDescription":   &hcldec.AttrSpec{Name: "image_description", Type: cty.String, Required: false},
		"Reboot":             &hcldec.AttrSpec{Name: "reboot", Type: cty.Bool, Required: false},
		"ForcePoweroff":      &hcldec.AttrSpec{Name: "force_poweroff", Type: cty.Bool, Required: false},
		"Sysprep":            &hcldec.AttrSpec{Name: "sysprep", Type: cty.Bool, Required: false},
		"ImageForceDelete":   &hcldec.AttrSpec{Name: "image_force_delete", Type: cty.Bool, Required: false},
		"ImageCopyRegions":   &hcldec.AttrSpec{Name: "image_copy_regions", Type: cty.List(cty.String), Required: false},
		"ImageShareAccounts": &hcldec.AttrSpec{Name: "image_share_accounts", Type: cty.List(cty.String), Required: false},
		"SkipValidation":     &hcldec.AttrSpec{Name: "skip_region_validation", Type: cty.Bool, Required: false},
	}
	return s
}
