// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package vagrantcloud

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Tag":                   &hcldec.AttrSpec{Name: "box_tag", Type: cty.String, Required: false},
		"Version":               &hcldec.AttrSpec{Name: "version", Type: cty.String, Required: false},
		"VersionDescription":    &hcldec.AttrSpec{Name: "version_description", Type: cty.String, Required: false},
		"NoRelease":             &hcldec.AttrSpec{Name: "no_release", Type: cty.Bool, Required: false},
		"AccessToken":           &hcldec.AttrSpec{Name: "access_token", Type: cty.String, Required: false},
		"VagrantCloudUrl":       &hcldec.AttrSpec{Name: "vagrant_cloud_url", Type: cty.String, Required: false},
		"InsecureSkipTLSVerify": &hcldec.AttrSpec{Name: "insecure_skip_tls_verify", Type: cty.Bool, Required: false},
		"BoxDownloadUrl":        &hcldec.AttrSpec{Name: "box_download_url", Type: cty.String, Required: false},
	}
	return s
}
