// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package vsphere_template

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Host":                &hcldec.AttrSpec{Name: "host", Type: cty.String, Required: false},
		"Insecure":            &hcldec.AttrSpec{Name: "insecure", Type: cty.Bool, Required: false},
		"Username":            &hcldec.AttrSpec{Name: "username", Type: cty.String, Required: false},
		"Password":            &hcldec.AttrSpec{Name: "password", Type: cty.String, Required: false},
		"Datacenter":          &hcldec.AttrSpec{Name: "datacenter", Type: cty.String, Required: false},
		"Folder":              &hcldec.AttrSpec{Name: "folder", Type: cty.String, Required: false},
		"SnapshotEnable":      &hcldec.AttrSpec{Name: "snapshot_enable", Type: cty.Bool, Required: false},
		"SnapshotName":        &hcldec.AttrSpec{Name: "snapshot_name", Type: cty.String, Required: false},
		"SnapshotDescription": &hcldec.AttrSpec{Name: "snapshot_description", Type: cty.String, Required: false},
	}
	return s
}
