// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package amazonimport

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"S3Bucket":        &hcldec.AttrSpec{Name: "s3_bucket_name", Type: cty.String, Required: false},
		"S3Key":           &hcldec.AttrSpec{Name: "s3_key_name", Type: cty.String, Required: false},
		"S3Encryption":    &hcldec.AttrSpec{Name: "s3_encryption", Type: cty.String, Required: false},
		"S3EncryptionKey": &hcldec.AttrSpec{Name: "s3_encryption_key", Type: cty.String, Required: false},
		"SkipClean":       &hcldec.AttrSpec{Name: "skip_clean", Type: cty.Bool, Required: false},
		"Tags":            &hcldec.BlockAttrsSpec{TypeName: "tags", ElementType: cty.String, Required: false},
		"Name":            &hcldec.AttrSpec{Name: "ami_name", Type: cty.String, Required: false},
		"Description":     &hcldec.AttrSpec{Name: "ami_description", Type: cty.String, Required: false},
		"Users":           &hcldec.AttrSpec{Name: "ami_users", Type: cty.List(cty.String), Required: false},
		"Groups":          &hcldec.AttrSpec{Name: "ami_groups", Type: cty.List(cty.String), Required: false},
		"Encrypt":         &hcldec.AttrSpec{Name: "ami_encrypt", Type: cty.Bool, Required: false},
		"KMSKey":          &hcldec.AttrSpec{Name: "ami_kms_key", Type: cty.String, Required: false},
		"LicenseType":     &hcldec.AttrSpec{Name: "license_type", Type: cty.String, Required: false},
		"RoleName":        &hcldec.AttrSpec{Name: "role_name", Type: cty.String, Required: false},
		"Format":          &hcldec.AttrSpec{Name: "format", Type: cty.String, Required: false},
	}
	for k, v := range (&Config{}).AccessConfig.HCL2Spec() {
		s[k] = v
	}
	return s
}
