// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package ansiblelocal

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Command":         &hcldec.AttrSpec{Name: "command", Type: cty.String, Required: false},
		"ExtraArguments":  &hcldec.AttrSpec{Name: "extra_arguments", Type: cty.List(cty.String), Required: false},
		"GroupVars":       &hcldec.AttrSpec{Name: "group_vars", Type: cty.String, Required: false},
		"HostVars":        &hcldec.AttrSpec{Name: "host_vars", Type: cty.String, Required: false},
		"PlaybookDir":     &hcldec.AttrSpec{Name: "playbook_dir", Type: cty.String, Required: false},
		"PlaybookFile":    &hcldec.AttrSpec{Name: "playbook_file", Type: cty.String, Required: false},
		"PlaybookFiles":   &hcldec.AttrSpec{Name: "playbook_files", Type: cty.List(cty.String), Required: false},
		"PlaybookPaths":   &hcldec.AttrSpec{Name: "playbook_paths", Type: cty.List(cty.String), Required: false},
		"RolePaths":       &hcldec.AttrSpec{Name: "role_paths", Type: cty.List(cty.String), Required: false},
		"StagingDir":      &hcldec.AttrSpec{Name: "staging_directory", Type: cty.String, Required: false},
		"CleanStagingDir": &hcldec.AttrSpec{Name: "clean_staging_directory", Type: cty.Bool, Required: false},
		"InventoryFile":   &hcldec.AttrSpec{Name: "inventory_file", Type: cty.String, Required: false},
		"InventoryGroups": &hcldec.AttrSpec{Name: "inventory_groups", Type: cty.List(cty.String), Required: false},
		"GalaxyFile":      &hcldec.AttrSpec{Name: "galaxy_file", Type: cty.String, Required: false},
		"GalaxyCommand":   &hcldec.AttrSpec{Name: "galaxycommand", Type: cty.String, Required: false},
	}
	return s
}
