// Code generated by "hcl2-schema -type ExportConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*ExportConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Format":     &hcldec.AttrSpec{Name: "format", Type: cty.String, Required: false},
		"ExportOpts": &hcldec.AttrSpec{Name: "export_opts", Type: cty.List(cty.String), Required: false},
	}
	return s
}
