// Code generated by "hcl2-schema -type GuestAdditionsConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*GuestAdditionsConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Communicator":       &hcldec.AttrSpec{Name: "communicator", Type: cty.String, Required: false},
		"GuestAdditionsMode": &hcldec.AttrSpec{Name: "guest_additions_mode", Type: cty.String, Required: false},
	}
	return s
}
