// Code generated by "hcl2-schema -type HWConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*HWConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"CpuCount":   &hcldec.AttrSpec{Name: "cpus", Type: cty.Number, Required: false},
		"MemorySize": &hcldec.AttrSpec{Name: "memory", Type: cty.Number, Required: false},
		"Sound":      &hcldec.AttrSpec{Name: "sound", Type: cty.String, Required: false},
		"USB":        &hcldec.AttrSpec{Name: "usb", Type: cty.Bool, Required: false},
	}
	return s
}
