// Code generated by "hcl2-schema -type RunConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*RunConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Headless":        &hcldec.AttrSpec{Name: "headless", Type: cty.Bool, Required: false},
		"VRDPBindAddress": &hcldec.AttrSpec{Name: "vrdp_bind_address", Type: cty.String, Required: false},
		"VRDPPortMin":     &hcldec.AttrSpec{Name: "vrdp_port_min", Type: cty.Number, Required: false},
		"VRDPPortMax":     &hcldec.AttrSpec{Name: "vrdp_port_max", Type: cty.Number, Required: false},
	}
	return s
}
