// Code generated by "hcl2-schema -type VBoxBundleConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*VBoxBundleConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"BundleISO": &hcldec.AttrSpec{Name: "bundle_iso", Type: cty.Bool, Required: false},
	}
	return s
}
