// Code generated by "hcl2-schema -type VBoxManageConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
)

func (*VBoxManageConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{}
	return s
}
