// Code generated by "hcl2-schema -type VBoxVersionConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*VBoxVersionConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Communicator":    &hcldec.AttrSpec{Name: "communicator", Type: cty.String, Required: false},
		"VBoxVersionFile": &hcldec.AttrSpec{Name: "virtualbox_version_file", Type: cty.String, Required: false},
	}
	return s
}
