// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package iso

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"DiskSize":                &hcldec.AttrSpec{Name: "disk_size", Type: cty.Number, Required: false},
		"GuestAdditionsMode":      &hcldec.AttrSpec{Name: "guest_additions_mode", Type: cty.String, Required: false},
		"GuestAdditionsPath":      &hcldec.AttrSpec{Name: "guest_additions_path", Type: cty.String, Required: false},
		"GuestAdditionsSHA256":    &hcldec.AttrSpec{Name: "guest_additions_sha256", Type: cty.String, Required: false},
		"GuestAdditionsURL":       &hcldec.AttrSpec{Name: "guest_additions_url", Type: cty.String, Required: false},
		"GuestAdditionsInterface": &hcldec.AttrSpec{Name: "guest_additions_interface", Type: cty.String, Required: false},
		"GuestOSType":             &hcldec.AttrSpec{Name: "guest_os_type", Type: cty.String, Required: false},
		"HardDriveDiscard":        &hcldec.AttrSpec{Name: "hard_drive_discard", Type: cty.Bool, Required: false},
		"HardDriveInterface":      &hcldec.AttrSpec{Name: "hard_drive_interface", Type: cty.String, Required: false},
		"SATAPortCount":           &hcldec.AttrSpec{Name: "sata_port_count", Type: cty.Number, Required: false},
		"HardDriveNonrotational":  &hcldec.AttrSpec{Name: "hard_drive_nonrotational", Type: cty.Bool, Required: false},
		"ISOInterface":            &hcldec.AttrSpec{Name: "iso_interface", Type: cty.String, Required: false},
		"KeepRegistered":          &hcldec.AttrSpec{Name: "keep_registered", Type: cty.Bool, Required: false},
		"SkipExport":              &hcldec.AttrSpec{Name: "skip_export", Type: cty.Bool, Required: false},
		"VMName":                  &hcldec.AttrSpec{Name: "vm_name", Type: cty.String, Required: false},
	}
	for k, v := range (&Config{}).HTTPConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).ISOConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).FloppyConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).BootConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).ExportConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).OutputConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).RunConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).ShutdownConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).SSHConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).HWConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).VBoxManageConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).VBoxVersionConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).VBoxBundleConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).GuestAdditionsConfig.HCL2Spec() {
		s[k] = v
	}
	return s
}
