// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package null

import (
	"github.com/hashicorp/hcl2/hcldec"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{}
	return s
}
