// Code generated by "hcl2-schema -type PrlctlVersionConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*PrlctlVersionConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"PrlctlVersionFile": &hcldec.AttrSpec{Name: "prlctl_version_file", Type: cty.String, Required: false},
	}
	return s
}
