// Code generated by "hcl2-schema -type ToolsConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*ToolsConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"ParallelsToolsFlavor":    &hcldec.AttrSpec{Name: "parallels_tools_flavor", Type: cty.String, Required: false},
		"ParallelsToolsGuestPath": &hcldec.AttrSpec{Name: "parallels_tools_guest_path", Type: cty.String, Required: false},
		"ParallelsToolsMode":      &hcldec.AttrSpec{Name: "parallels_tools_mode", Type: cty.String, Required: false},
	}
	return s
}
