// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package dockerimport

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Repository": &hcldec.AttrSpec{Name: "repository", Type: cty.String, Required: false},
		"Tag":        &hcldec.AttrSpec{Name: "tag", Type: cty.String, Required: false},
		"Changes":    &hcldec.AttrSpec{Name: "changes", Type: cty.List(cty.String), Required: false},
	}
	return s
}
