// Code generated by "hcl2-schema -type AccessConfig"; DO NOT EDIT.\n

package openstack

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*AccessConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Username":                    &hcldec.AttrSpec{Name: "username", Type: cty.String, Required: false},
		"UserID":                      &hcldec.AttrSpec{Name: "user_id", Type: cty.String, Required: false},
		"Password":                    &hcldec.AttrSpec{Name: "password", Type: cty.String, Required: false},
		"IdentityEndpoint":            &hcldec.AttrSpec{Name: "identity_endpoint", Type: cty.String, Required: false},
		"TenantID":                    &hcldec.AttrSpec{Name: "tenant_id", Type: cty.String, Required: false},
		"TenantName":                  &hcldec.AttrSpec{Name: "tenant_name", Type: cty.String, Required: false},
		"DomainID":                    &hcldec.AttrSpec{Name: "domain_id", Type: cty.String, Required: false},
		"DomainName":                  &hcldec.AttrSpec{Name: "domain_name", Type: cty.String, Required: false},
		"Insecure":                    &hcldec.AttrSpec{Name: "insecure", Type: cty.Bool, Required: false},
		"Region":                      &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"EndpointType":                &hcldec.AttrSpec{Name: "endpoint_type", Type: cty.String, Required: false},
		"CACertFile":                  &hcldec.AttrSpec{Name: "cacert", Type: cty.String, Required: false},
		"ClientCertFile":              &hcldec.AttrSpec{Name: "cert", Type: cty.String, Required: false},
		"ClientKeyFile":               &hcldec.AttrSpec{Name: "key", Type: cty.String, Required: false},
		"Token":                       &hcldec.AttrSpec{Name: "token", Type: cty.String, Required: false},
		"ApplicationCredentialName":   &hcldec.AttrSpec{Name: "application_credential_name", Type: cty.String, Required: false},
		"ApplicationCredentialID":     &hcldec.AttrSpec{Name: "application_credential_id", Type: cty.String, Required: false},
		"ApplicationCredentialSecret": &hcldec.AttrSpec{Name: "application_credential_secret", Type: cty.String, Required: false},
		"Cloud":                       &hcldec.AttrSpec{Name: "cloud", Type: cty.String, Required: false},
	}
	return s
}
