// Code generated by "hcl2-schema -type ImageConfig"; DO NOT EDIT.\n

package openstack

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*ImageConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"ImageName":       &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"ImageMetadata":   &hcldec.BlockAttrsSpec{TypeName: "metadata", ElementType: cty.String, Required: false},
		"ImageVisibility": &hcldec.AttrSpec{Name: "image_visibility", Type: cty.String, Required: false},
		"ImageMembers":    &hcldec.AttrSpec{Name: "image_members", Type: cty.List(cty.String), Required: false},
		"ImageDiskFormat": &hcldec.AttrSpec{Name: "image_disk_format", Type: cty.String, Required: false},
		"ImageTags":       &hcldec.AttrSpec{Name: "image_tags", Type: cty.List(cty.String), Required: false},
		"ImageMinDisk":    &hcldec.AttrSpec{Name: "image_min_disk", Type: cty.Number, Required: false},
	}
	return s
}
