// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package vagrant

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"CompressionLevel":             &hcldec.AttrSpec{Name: "compression_level", Type: cty.Number, Required: false},
		"Include":                      &hcldec.AttrSpec{Name: "include", Type: cty.List(cty.String), Required: false},
		"OutputPath":                   &hcldec.AttrSpec{Name: "output", Type: cty.String, Required: false},
		"VagrantfileTemplate":          &hcldec.AttrSpec{Name: "vagrantfile_template", Type: cty.String, Required: false},
		"VagrantfileTemplateGenerated": &hcldec.AttrSpec{Name: "vagrantfile_template_generated", Type: cty.Bool, Required: false},
	}
	return s
}
