// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package yandex

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Endpoint":              &hcldec.AttrSpec{Name: "endpoint", Type: cty.String, Required: false},
		"FolderID":              &hcldec.AttrSpec{Name: "folder_id", Type: cty.String, Required: false},
		"ServiceAccountKeyFile": &hcldec.AttrSpec{Name: "service_account_key_file", Type: cty.String, Required: false},
		"Token":                 &hcldec.AttrSpec{Name: "token", Type: cty.String, Required: false},
		"DiskName":              &hcldec.AttrSpec{Name: "disk_name", Type: cty.String, Required: false},
		"DiskSizeGb":            &hcldec.AttrSpec{Name: "disk_size_gb", Type: cty.Number, Required: false},
		"DiskType":              &hcldec.AttrSpec{Name: "disk_type", Type: cty.String, Required: false},
		"ImageDescription":      &hcldec.AttrSpec{Name: "image_description", Type: cty.String, Required: false},
		"ImageFamily":           &hcldec.AttrSpec{Name: "image_family", Type: cty.String, Required: false},
		"ImageLabels":           &hcldec.BlockAttrsSpec{TypeName: "image_labels", ElementType: cty.String, Required: false},
		"ImageName":             &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"ImageProductIDs":       &hcldec.AttrSpec{Name: "image_product_ids", Type: cty.List(cty.String), Required: false},
		"InstanceCores":         &hcldec.AttrSpec{Name: "instance_cores", Type: cty.Number, Required: false},
		"InstanceGpus":          &hcldec.AttrSpec{Name: "instance_gpus", Type: cty.Number, Required: false},
		"InstanceMemory":        &hcldec.AttrSpec{Name: "instance_mem_gb", Type: cty.Number, Required: false},
		"InstanceName":          &hcldec.AttrSpec{Name: "instance_name", Type: cty.String, Required: false},
		"Labels":                &hcldec.BlockAttrsSpec{TypeName: "labels", ElementType: cty.String, Required: false},
		"PlatformID":            &hcldec.AttrSpec{Name: "platform_id", Type: cty.String, Required: false},
		"MaxRetries":            &hcldec.AttrSpec{Name: "max_retries", Type: cty.Number, Required: false},
		"Metadata":              &hcldec.BlockAttrsSpec{TypeName: "metadata", ElementType: cty.String, Required: false},
		"MetadataFromFile":      &hcldec.BlockAttrsSpec{TypeName: "metadata_from_file", ElementType: cty.String, Required: false},
		"Preemptible":           &hcldec.AttrSpec{Name: "preemptible", Type: cty.Bool, Required: false},
		"SerialLogFile":         &hcldec.AttrSpec{Name: "serial_log_file", Type: cty.String, Required: false},
		"SourceImageFamily":     &hcldec.AttrSpec{Name: "source_image_family", Type: cty.String, Required: false},
		"SourceImageFolderID":   &hcldec.AttrSpec{Name: "source_image_folder_id", Type: cty.String, Required: false},
		"SourceImageID":         &hcldec.AttrSpec{Name: "source_image_id", Type: cty.String, Required: false},
		"SourceImageName":       &hcldec.AttrSpec{Name: "source_image_name", Type: cty.String, Required: false},
		"SubnetID":              &hcldec.AttrSpec{Name: "subnet_id", Type: cty.String, Required: false},
		"UseIPv4Nat":            &hcldec.AttrSpec{Name: "use_ipv4_nat", Type: cty.Bool, Required: false},
		"UseIPv6":               &hcldec.AttrSpec{Name: "use_ipv6", Type: cty.Bool, Required: false},
		"UseInternalIP":         &hcldec.AttrSpec{Name: "use_internal_ip", Type: cty.Bool, Required: false},
		"Zone":                  &hcldec.AttrSpec{Name: "zone", Type: cty.String, Required: false},
		"StateTimeout":          &hcldec.AttrSpec{Name: "state_timeout", Type: cty.String, Required: false},
	}
	return s
}
