// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package exoscaleimport

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"SkipClean":               &hcldec.AttrSpec{Name: "skip_clean", Type: cty.Bool, Required: false},
		"SOSEndpoint":             &hcldec.AttrSpec{Name: "sos_endpoint", Type: cty.String, Required: false},
		"APIEndpoint":             &hcldec.AttrSpec{Name: "api_endpoint", Type: cty.String, Required: false},
		"APIKey":                  &hcldec.AttrSpec{Name: "api_key", Type: cty.String, Required: false},
		"APISecret":               &hcldec.AttrSpec{Name: "api_secret", Type: cty.String, Required: false},
		"ImageBucket":             &hcldec.AttrSpec{Name: "image_bucket", Type: cty.String, Required: false},
		"TemplateZone":            &hcldec.AttrSpec{Name: "template_zone", Type: cty.String, Required: false},
		"TemplateName":            &hcldec.AttrSpec{Name: "template_name", Type: cty.String, Required: false},
		"TemplateDescription":     &hcldec.AttrSpec{Name: "template_description", Type: cty.String, Required: false},
		"TemplateUsername":        &hcldec.AttrSpec{Name: "template_username", Type: cty.String, Required: false},
		"TemplateDisablePassword": &hcldec.AttrSpec{Name: "template_disable_password", Type: cty.Bool, Required: false},
		"TemplateDisableSSHKey":   &hcldec.AttrSpec{Name: "template_disable_sshkey", Type: cty.Bool, Required: false},
	}
	return s
}
