// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package shell

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"ExecuteCommand":    &hcldec.AttrSpec{Name: "execute_command", Type: cty.String, Required: false},
		"StartRetryTimeout": &hcldec.AttrSpec{Name: "start_retry_timeout", Type: cty.String, Required: false},
		"EnvVarFormat":      &hcldec.AttrSpec{Name: "env_var_format", Type: cty.String, Required: false},
	}
	for k, v := range (&Config{}).Provisioner.HCL2Spec() {
		s[k] = v
	}
	return s
}
