// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package compress

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"OutputPath":       &hcldec.AttrSpec{Name: "output", Type: cty.String, Required: false},
		"Format":           &hcldec.AttrSpec{Name: "format", Type: cty.String, Required: false},
		"CompressionLevel": &hcldec.AttrSpec{Name: "compression_level", Type: cty.Number, Required: false},
		"Archive":          &hcldec.AttrSpec{Name: "archive", Type: cty.String, Required: false},
		"Algorithm":        &hcldec.AttrSpec{Name: "algorithm", Type: cty.String, Required: false},
	}
	return s
}
