// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package ansible

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Command":              &hcldec.AttrSpec{Name: "command", Type: cty.String, Required: false},
		"ExtraArguments":       &hcldec.AttrSpec{Name: "extra_arguments", Type: cty.List(cty.String), Required: false},
		"AnsibleEnvVars":       &hcldec.AttrSpec{Name: "ansible_env_vars", Type: cty.List(cty.String), Required: false},
		"PlaybookFile":         &hcldec.AttrSpec{Name: "playbook_file", Type: cty.String, Required: false},
		"Groups":               &hcldec.AttrSpec{Name: "groups", Type: cty.List(cty.String), Required: false},
		"EmptyGroups":          &hcldec.AttrSpec{Name: "empty_groups", Type: cty.List(cty.String), Required: false},
		"HostAlias":            &hcldec.AttrSpec{Name: "host_alias", Type: cty.String, Required: false},
		"User":                 &hcldec.AttrSpec{Name: "user", Type: cty.String, Required: false},
		"LocalPort":            &hcldec.AttrSpec{Name: "local_port", Type: cty.Number, Required: false},
		"SSHHostKeyFile":       &hcldec.AttrSpec{Name: "ssh_host_key_file", Type: cty.String, Required: false},
		"SSHAuthorizedKeyFile": &hcldec.AttrSpec{Name: "ssh_authorized_key_file", Type: cty.String, Required: false},
		"SFTPCmd":              &hcldec.AttrSpec{Name: "sftp_command", Type: cty.String, Required: false},
		"SkipVersionCheck":     &hcldec.AttrSpec{Name: "skip_version_check", Type: cty.Bool, Required: false},
		"UseSFTP":              &hcldec.AttrSpec{Name: "use_sftp", Type: cty.Bool, Required: false},
		"InventoryDirectory":   &hcldec.AttrSpec{Name: "inventory_directory", Type: cty.String, Required: false},
		"InventoryFile":        &hcldec.AttrSpec{Name: "inventory_file", Type: cty.String, Required: false},
		"GalaxyFile":           &hcldec.AttrSpec{Name: "galaxy_file", Type: cty.String, Required: false},
		"GalaxyCommand":        &hcldec.AttrSpec{Name: "galaxy_command", Type: cty.String, Required: false},
		"GalaxyForceInstall":   &hcldec.AttrSpec{Name: "galaxy_force_install", Type: cty.Bool, Required: false},
		"RolesPath":            &hcldec.AttrSpec{Name: "roles_path", Type: cty.String, Required: false},
	}
	return s
}
