// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package breakpoint

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Note":    &hcldec.AttrSpec{Name: "note", Type: cty.String, Required: false},
		"Disable": &hcldec.AttrSpec{Name: "disable", Type: cty.Bool, Required: false},
	}
	return s
}
