// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package file

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Source":      &hcldec.AttrSpec{Name: "source", Type: cty.String, Required: false},
		"Sources":     &hcldec.AttrSpec{Name: "sources", Type: cty.List(cty.String), Required: false},
		"Destination": &hcldec.AttrSpec{Name: "destination", Type: cty.String, Required: false},
		"Direction":   &hcldec.AttrSpec{Name: "direction", Type: cty.String, Required: false},
		"Generated":   &hcldec.AttrSpec{Name: "generated", Type: cty.Bool, Required: false},
	}
	return s
}
