// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package digitalocean

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"APIToken":          &hcldec.AttrSpec{Name: "api_token", Type: cty.String, Required: false},
		"APIURL":            &hcldec.AttrSpec{Name: "api_url", Type: cty.String, Required: false},
		"Region":            &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"Size":              &hcldec.AttrSpec{Name: "size", Type: cty.String, Required: false},
		"Image":             &hcldec.AttrSpec{Name: "image", Type: cty.String, Required: false},
		"PrivateNetworking": &hcldec.AttrSpec{Name: "private_networking", Type: cty.Bool, Required: false},
		"Monitoring":        &hcldec.AttrSpec{Name: "monitoring", Type: cty.Bool, Required: false},
		"IPv6":              &hcldec.AttrSpec{Name: "ipv6", Type: cty.Bool, Required: false},
		"SnapshotName":      &hcldec.AttrSpec{Name: "snapshot_name", Type: cty.String, Required: false},
		"SnapshotRegions":   &hcldec.AttrSpec{Name: "snapshot_regions", Type: cty.List(cty.String), Required: false},
		"StateTimeout":      &hcldec.AttrSpec{Name: "state_timeout", Type: cty.String, Required: false},
		"SnapshotTimeout":   &hcldec.AttrSpec{Name: "snapshot_timeout", Type: cty.String, Required: false},
		"DropletName":       &hcldec.AttrSpec{Name: "droplet_name", Type: cty.String, Required: false},
		"UserData":          &hcldec.AttrSpec{Name: "user_data", Type: cty.String, Required: false},
		"UserDataFile":      &hcldec.AttrSpec{Name: "user_data_file", Type: cty.String, Required: false},
		"Tags":              &hcldec.AttrSpec{Name: "tags", Type: cty.List(cty.String), Required: false},
	}
	return s
}
