// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package googlecomputeexport

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"AccountFile":         &hcldec.AttrSpec{Name: "account_file", Type: cty.String, Required: false},
		"DiskSizeGb":          &hcldec.AttrSpec{Name: "disk_size", Type: cty.Number, Required: false},
		"DiskType":            &hcldec.AttrSpec{Name: "disk_type", Type: cty.String, Required: false},
		"MachineType":         &hcldec.AttrSpec{Name: "machine_type", Type: cty.String, Required: false},
		"Network":             &hcldec.AttrSpec{Name: "network", Type: cty.String, Required: false},
		"Paths":               &hcldec.AttrSpec{Name: "paths", Type: cty.List(cty.String), Required: false},
		"Subnetwork":          &hcldec.AttrSpec{Name: "subnetwork", Type: cty.String, Required: false},
		"VaultGCPOauthEngine": &hcldec.AttrSpec{Name: "vault_gcp_oauth_engine", Type: cty.String, Required: false},
		"Zone":                &hcldec.AttrSpec{Name: "zone", Type: cty.String, Required: false},
	}
	return s
}
