// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package restart

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"RestartCommand":      &hcldec.AttrSpec{Name: "restart_command", Type: cty.String, Required: false},
		"RestartCheckCommand": &hcldec.AttrSpec{Name: "restart_check_command", Type: cty.String, Required: false},
		"RestartTimeout":      &hcldec.AttrSpec{Name: "restart_timeout", Type: cty.String, Required: false},
		"CheckKey":            &hcldec.AttrSpec{Name: "check_registry", Type: cty.Bool, Required: false},
		"RegistryKeys":        &hcldec.AttrSpec{Name: "registry_keys", Type: cty.List(cty.String), Required: false},
	}
	return s
}
