// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package dockerpush

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Login":         &hcldec.AttrSpec{Name: "login", Type: cty.Bool, Required: false},
		"LoginUsername": &hcldec.AttrSpec{Name: "login_username", Type: cty.String, Required: false},
		"LoginPassword": &hcldec.AttrSpec{Name: "login_password", Type: cty.String, Required: false},
		"LoginServer":   &hcldec.AttrSpec{Name: "login_server", Type: cty.String, Required: false},
		"EcrLogin":      &hcldec.AttrSpec{Name: "ecr_login", Type: cty.Bool, Required: false},
	}
	for k, v := range (&Config{}).AwsAccessConfig.HCL2Spec() {
		s[k] = v
	}
	return s
}
