// Code generated by "hcl2-schema -type Provisioner"; DO NOT EDIT.\n

package sleep

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Provisioner) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Duration": &hcldec.AttrSpec{Name: "duration", Type: cty.String, Required: false},
	}
	return s
}
