// Code generated by "hcl2-schema -type FloppyConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*FloppyConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"FloppyFiles":       &hcldec.AttrSpec{Name: "floppy_files", Type: cty.List(cty.String), Required: false},
		"FloppyDirectories": &hcldec.AttrSpec{Name: "floppy_dirs", Type: cty.List(cty.String), Required: false},
		"FloppyLabel":       &hcldec.AttrSpec{Name: "floppy_label", Type: cty.String, Required: false},
	}
	return s
}
