// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package dockersave

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Path": &hcldec.AttrSpec{Name: "path", Type: cty.String, Required: false},
	}
	return s
}
