// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package client

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"CloudEnvironmentName": &hcldec.AttrSpec{Name: "cloud_environment_name", Type: cty.String, Required: false},
		"ClientID":             &hcldec.AttrSpec{Name: "client_id", Type: cty.String, Required: false},
		"ClientSecret":         &hcldec.AttrSpec{Name: "client_secret", Type: cty.String, Required: false},
		"ClientCertPath":       &hcldec.AttrSpec{Name: "client_cert_path", Type: cty.String, Required: false},
		"ClientJWT":            &hcldec.AttrSpec{Name: "client_jwt", Type: cty.String, Required: false},
		"ObjectID":             &hcldec.AttrSpec{Name: "object_id", Type: cty.String, Required: false},
		"TenantID":             &hcldec.AttrSpec{Name: "tenant_id", Type: cty.String, Required: false},
		"SubscriptionID":       &hcldec.AttrSpec{Name: "subscription_id", Type: cty.String, Required: false},
	}
	return s
}
