// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package artifice

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Files": &hcldec.AttrSpec{Name: "files", Type: cty.List(cty.String), Required: false},
		"Keep":  &hcldec.AttrSpec{Name: "keep_input_artifact", Type: cty.Bool, Required: false},
	}
	return s
}
