// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package lxd

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"OutputImage":       &hcldec.AttrSpec{Name: "output_image", Type: cty.String, Required: false},
		"ContainerName":     &hcldec.AttrSpec{Name: "container_name", Type: cty.String, Required: false},
		"CommandWrapper":    &hcldec.AttrSpec{Name: "command_wrapper", Type: cty.String, Required: false},
		"Image":             &hcldec.AttrSpec{Name: "image", Type: cty.String, Required: false},
		"Profile":           &hcldec.AttrSpec{Name: "profile", Type: cty.String, Required: false},
		"InitSleep":         &hcldec.AttrSpec{Name: "init_sleep", Type: cty.String, Required: false},
		"PublishProperties": &hcldec.BlockAttrsSpec{TypeName: "publish_properties", ElementType: cty.String, Required: false},
		"LaunchConfig":      &hcldec.BlockAttrsSpec{TypeName: "launch_config", ElementType: cty.String, Required: false},
	}
	return s
}
