// Code generated by "hcl2-schema -type JDCloudCredentialConfig"; DO NOT EDIT.\n

package jdcloud

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*JDCloudCredentialConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"AccessKey": &hcldec.AttrSpec{Name: "access_key", Type: cty.String, Required: false},
		"SecretKey": &hcldec.AttrSpec{Name: "secret_key", Type: cty.String, Required: false},
		"RegionId":  &hcldec.AttrSpec{Name: "region_id", Type: cty.String, Required: false},
		"Az":        &hcldec.AttrSpec{Name: "az", Type: cty.String, Required: false},
	}
	return s
}
