// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package pvm

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"SourcePath":     &hcldec.AttrSpec{Name: "source_path", Type: cty.String, Required: false},
		"SkipCompaction": &hcldec.AttrSpec{Name: "skip_compaction", Type: cty.Bool, Required: false},
		"VMName":         &hcldec.AttrSpec{Name: "vm_name", Type: cty.String, Required: false},
		"ReassignMAC":    &hcldec.AttrSpec{Name: "reassign_mac", Type: cty.Bool, Required: false},
	}
	for k, v := range (&Config{}).FloppyConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).OutputConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).PrlctlConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).PrlctlPostConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).PrlctlVersionConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).SSHConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).ShutdownConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).BootConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).ToolsConfig.HCL2Spec() {
		s[k] = v
	}
	return s
}
