// Code generated by "hcl2-schema -type DriverConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*DriverConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"FusionAppPath":           &hcldec.AttrSpec{Name: "fusion_app_path", Type: cty.String, Required: false},
		"RemoteType":              &hcldec.AttrSpec{Name: "remote_type", Type: cty.String, Required: false},
		"RemoteDatastore":         &hcldec.AttrSpec{Name: "remote_datastore", Type: cty.String, Required: false},
		"RemoteCacheDatastore":    &hcldec.AttrSpec{Name: "remote_cache_datastore", Type: cty.String, Required: false},
		"RemoteCacheDirectory":    &hcldec.AttrSpec{Name: "remote_cache_directory", Type: cty.String, Required: false},
		"RemoteHost":              &hcldec.AttrSpec{Name: "remote_host", Type: cty.String, Required: false},
		"RemotePort":              &hcldec.AttrSpec{Name: "remote_port", Type: cty.Number, Required: false},
		"RemoteUser":              &hcldec.AttrSpec{Name: "remote_username", Type: cty.String, Required: false},
		"RemotePassword":          &hcldec.AttrSpec{Name: "remote_password", Type: cty.String, Required: false},
		"RemotePrivateKey":        &hcldec.AttrSpec{Name: "remote_private_key_file", Type: cty.String, Required: false},
		"SkipValidateCredentials": &hcldec.AttrSpec{Name: "skip_validate_credentials", Type: cty.Bool, Required: false},
	}
	return s
}
