// Code generated by "hcl2-schema -type ExportConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*ExportConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Format":         &hcldec.AttrSpec{Name: "format", Type: cty.String, Required: false},
		"OVFToolOptions": &hcldec.AttrSpec{Name: "ovftool_options", Type: cty.List(cty.String), Required: false},
		"SkipExport":     &hcldec.AttrSpec{Name: "skip_export", Type: cty.Bool, Required: false},
		"KeepRegistered": &hcldec.AttrSpec{Name: "keep_registered", Type: cty.Bool, Required: false},
		"SkipCompaction": &hcldec.AttrSpec{Name: "skip_compaction", Type: cty.Bool, Required: false},
	}
	return s
}
