// Code generated by "hcl2-schema -type HWConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*HWConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"CpuCount":           &hcldec.AttrSpec{Name: "cpus", Type: cty.Number, Required: false},
		"MemorySize":         &hcldec.AttrSpec{Name: "memory", Type: cty.Number, Required: false},
		"CoreCount":          &hcldec.AttrSpec{Name: "cores", Type: cty.Number, Required: false},
		"Network":            &hcldec.AttrSpec{Name: "network", Type: cty.String, Required: false},
		"NetworkAdapterType": &hcldec.AttrSpec{Name: "network_adapter_type", Type: cty.String, Required: false},
		"Sound":              &hcldec.AttrSpec{Name: "sound", Type: cty.Bool, Required: false},
		"USB":                &hcldec.AttrSpec{Name: "usb", Type: cty.Bool, Required: false},
		"Serial":             &hcldec.AttrSpec{Name: "serial", Type: cty.String, Required: false},
		"Parallel":           &hcldec.AttrSpec{Name: "parallel", Type: cty.String, Required: false},
	}
	return s
}
