// Code generated by "hcl2-schema -type OutputConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*OutputConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"OutputDir": &hcldec.AttrSpec{Name: "output_directory", Type: cty.String, Required: false},
	}
	return s
}
