// Code generated by "hcl2-schema -type RunConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*RunConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Headless":           &hcldec.AttrSpec{Name: "headless", Type: cty.Bool, Required: false},
		"VNCBindAddress":     &hcldec.AttrSpec{Name: "vnc_bind_address", Type: cty.String, Required: false},
		"VNCPortMin":         &hcldec.AttrSpec{Name: "vnc_port_min", Type: cty.Number, Required: false},
		"VNCPortMax":         &hcldec.AttrSpec{Name: "vnc_port_max", Type: cty.Number, Required: false},
		"VNCDisablePassword": &hcldec.AttrSpec{Name: "vnc_disable_password", Type: cty.Bool, Required: false},
	}
	return s
}
