// Code generated by "hcl2-schema -type SSHConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*SSHConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"SSHSkipRequestPty": &hcldec.AttrSpec{Name: "ssh_skip_request_pty", Type: cty.Bool, Required: false},
		"SSHWaitTimeout":    &hcldec.AttrSpec{Name: "ssh_wait_timeout", Type: cty.String, Required: false},
	}
	return s
}
