// Code generated by "hcl2-schema -type ToolsConfig"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*ToolsConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"ToolsUploadFlavor": &hcldec.AttrSpec{Name: "tools_upload_flavor", Type: cty.String, Required: false},
		"ToolsUploadPath":   &hcldec.AttrSpec{Name: "tools_upload_path", Type: cty.String, Required: false},
	}
	return s
}
