// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package oci

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"AccessCfgFile":        &hcldec.AttrSpec{Name: "access_cfg_file", Type: cty.String, Required: false},
		"AccessCfgFileAccount": &hcldec.AttrSpec{Name: "access_cfg_file_account", Type: cty.String, Required: false},
		"UserID":               &hcldec.AttrSpec{Name: "user_ocid", Type: cty.String, Required: false},
		"TenancyID":            &hcldec.AttrSpec{Name: "tenancy_ocid", Type: cty.String, Required: false},
		"Region":               &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"Fingerprint":          &hcldec.AttrSpec{Name: "fingerprint", Type: cty.String, Required: false},
		"KeyFile":              &hcldec.AttrSpec{Name: "key_file", Type: cty.String, Required: false},
		"PassPhrase":           &hcldec.AttrSpec{Name: "pass_phrase", Type: cty.String, Required: false},
		"UsePrivateIP":         &hcldec.AttrSpec{Name: "use_private_ip", Type: cty.Bool, Required: false},
		"AvailabilityDomain":   &hcldec.AttrSpec{Name: "availability_domain", Type: cty.String, Required: false},
		"CompartmentID":        &hcldec.AttrSpec{Name: "compartment_ocid", Type: cty.String, Required: false},
		"BaseImageID":          &hcldec.AttrSpec{Name: "base_image_ocid", Type: cty.String, Required: false},
		"Shape":                &hcldec.AttrSpec{Name: "shape", Type: cty.String, Required: false},
		"ImageName":            &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"InstanceName":         &hcldec.AttrSpec{Name: "instance_name", Type: cty.String, Required: false},
		"Metadata":             &hcldec.BlockAttrsSpec{TypeName: "metadata", ElementType: cty.String, Required: false},
		"UserData":             &hcldec.AttrSpec{Name: "user_data", Type: cty.String, Required: false},
		"UserDataFile":         &hcldec.AttrSpec{Name: "user_data_file", Type: cty.String, Required: false},
		"SubnetID":             &hcldec.AttrSpec{Name: "subnet_ocid", Type: cty.String, Required: false},
		"Tags":                 &hcldec.BlockAttrsSpec{TypeName: "tags", ElementType: cty.String, Required: false},
	}
	return s
}
