// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package checksum

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Keep":          &hcldec.AttrSpec{Name: "keep_input_artifact", Type: cty.Bool, Required: false},
		"ChecksumTypes": &hcldec.AttrSpec{Name: "checksum_types", Type: cty.List(cty.String), Required: false},
		"OutputPath":    &hcldec.AttrSpec{Name: "output", Type: cty.String, Required: false},
	}
	return s
}
