// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package linode

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"PersonalAccessToken": &hcldec.AttrSpec{Name: "linode_token", Type: cty.String, Required: false},
		"Region":              &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"InstanceType":        &hcldec.AttrSpec{Name: "instance_type", Type: cty.String, Required: false},
		"Label":               &hcldec.AttrSpec{Name: "instance_label", Type: cty.String, Required: false},
		"Tags":                &hcldec.AttrSpec{Name: "instance_tags", Type: cty.List(cty.String), Required: false},
		"Image":               &hcldec.AttrSpec{Name: "image", Type: cty.String, Required: false},
		"SwapSize":            &hcldec.AttrSpec{Name: "swap_size", Type: cty.Number, Required: false},
		"RootPass":            &hcldec.AttrSpec{Name: "root_pass", Type: cty.String, Required: false},
		"RootSSHKey":          &hcldec.AttrSpec{Name: "root_ssh_key", Type: cty.String, Required: false},
		"ImageLabel":          &hcldec.AttrSpec{Name: "image_label", Type: cty.String, Required: false},
		"Description":         &hcldec.AttrSpec{Name: "image_description", Type: cty.String, Required: false},
		"RawStateTimeout":     &hcldec.AttrSpec{Name: "state_timeout", Type: cty.String, Required: false},
	}
	return s
}
