// Code generated by "hcl2-schema -type ImageConfig,ImageDestination"; DO NOT EDIT.\n

package uhost

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*ImageConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"ImageName":              &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"ImageDescription":       &hcldec.AttrSpec{Name: "image_description", Type: cty.String, Required: false},
		"image_copy_to_mappings": &hcldec.BlockListSpec{TypeName: "[]ImageDestination", Nested: hcldec.ObjectSpec((&ImageConfig{}).ImageDestinations[0].HCL2Spec())},
	}
	return s
}

func (*ImageDestination) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"ProjectId":   &hcldec.AttrSpec{Name: "project_id", Type: cty.String, Required: false},
		"Region":      &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"Name":        &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"Description": &hcldec.AttrSpec{Name: "description", Type: cty.String, Required: false},
	}
	return s
}
