// Code generated by "hcl2-schema -type RunConfig"; DO NOT EDIT.\n

package uhost

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*RunConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Zone":            &hcldec.AttrSpec{Name: "availability_zone", Type: cty.String, Required: false},
		"SourceImageId":   &hcldec.AttrSpec{Name: "source_image_id", Type: cty.String, Required: false},
		"InstanceType":    &hcldec.AttrSpec{Name: "instance_type", Type: cty.String, Required: false},
		"InstanceName":    &hcldec.AttrSpec{Name: "instance_name", Type: cty.String, Required: false},
		"BootDiskType":    &hcldec.AttrSpec{Name: "boot_disk_type", Type: cty.String, Required: false},
		"VPCId":           &hcldec.AttrSpec{Name: "vpc_id", Type: cty.String, Required: false},
		"SubnetId":        &hcldec.AttrSpec{Name: "subnet_id", Type: cty.String, Required: false},
		"SecurityGroupId": &hcldec.AttrSpec{Name: "security_group_id", Type: cty.String, Required: false},
		"UseSSHPrivateIp": &hcldec.AttrSpec{Name: "use_ssh_private_ip", Type: cty.Bool, Required: false},
	}
	return s
}
