// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package inspec

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Command":              &hcldec.AttrSpec{Name: "command", Type: cty.String, Required: false},
		"SubCommand":           &hcldec.AttrSpec{Name: "subcommand", Type: cty.String, Required: false},
		"ExtraArguments":       &hcldec.AttrSpec{Name: "extra_arguments", Type: cty.List(cty.String), Required: false},
		"InspecEnvVars":        &hcldec.AttrSpec{Name: "inspec_env_vars", Type: cty.List(cty.String), Required: false},
		"Profile":              &hcldec.AttrSpec{Name: "profile", Type: cty.String, Required: false},
		"AttributesDirectory":  &hcldec.AttrSpec{Name: "attributes_directory", Type: cty.String, Required: false},
		"AttributesFiles":      &hcldec.AttrSpec{Name: "attributes", Type: cty.List(cty.String), Required: false},
		"Backend":              &hcldec.AttrSpec{Name: "backend", Type: cty.String, Required: false},
		"User":                 &hcldec.AttrSpec{Name: "user", Type: cty.String, Required: false},
		"Host":                 &hcldec.AttrSpec{Name: "host", Type: cty.String, Required: false},
		"LocalPort":            &hcldec.AttrSpec{Name: "local_port", Type: cty.Number, Required: false},
		"SSHHostKeyFile":       &hcldec.AttrSpec{Name: "ssh_host_key_file", Type: cty.String, Required: false},
		"SSHAuthorizedKeyFile": &hcldec.AttrSpec{Name: "ssh_authorized_key_file", Type: cty.String, Required: false},
	}
	return s
}
