// Code generated by "hcl2-schema -type AccessConfig"; DO NOT EDIT.\n

package triton

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*AccessConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Endpoint":              &hcldec.AttrSpec{Name: "triton_url", Type: cty.String, Required: false},
		"Account":               &hcldec.AttrSpec{Name: "triton_account", Type: cty.String, Required: false},
		"Username":              &hcldec.AttrSpec{Name: "triton_user", Type: cty.String, Required: false},
		"KeyID":                 &hcldec.AttrSpec{Name: "triton_key_id", Type: cty.String, Required: false},
		"KeyMaterial":           &hcldec.AttrSpec{Name: "triton_key_material", Type: cty.String, Required: false},
		"InsecureSkipTLSVerify": &hcldec.AttrSpec{Name: "insecure_skip_tls_verify", Type: cty.Bool, Required: false},
	}
	return s
}
