// Code generated by "hcl2-schema -type Config"; DO NOT EDIT.\n

package triton

import (
	"github.com/hashicorp/hcl2/hcldec"
)

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{}
	for k, v := range (&Config{}).AccessConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).SourceMachineConfig.HCL2Spec() {
		s[k] = v
	}
	for k, v := range (&Config{}).TargetImageConfig.HCL2Spec() {
		s[k] = v
	}
	return s
}
