// Code generated by "hcl2-schema -type TargetImageConfig"; DO NOT EDIT.\n

package triton

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*TargetImageConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"ImageName":        &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"ImageVersion":     &hcldec.AttrSpec{Name: "image_version", Type: cty.String, Required: false},
		"ImageDescription": &hcldec.AttrSpec{Name: "image_description", Type: cty.String, Required: false},
		"ImageHomepage":    &hcldec.AttrSpec{Name: "image_homepage", Type: cty.String, Required: false},
		"ImageEULA":        &hcldec.AttrSpec{Name: "image_eula_url", Type: cty.String, Required: false},
		"ImageACL":         &hcldec.AttrSpec{Name: "image_acls", Type: cty.List(cty.String), Required: false},
		"ImageTags":        &hcldec.BlockAttrsSpec{TypeName: "image_tags", ElementType: cty.String, Required: false},
	}
	return s
}
